name: Build and Deploy
on:
  push:
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              cd /root/tmp
              rm -rf /root/tmp/vue-project
              git clone 
              cd /root/tmp/vue-project
              chmod +x ./deploy.sh
              ./deploy.sh